name: conoll
description: "A comunication app in school"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  file_picker: ^10.3.2
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.0
  material_symbols_icons: ^4.2858.1
  supabase_flutter: ^2.9.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
